### ISSUE TITLE
Stochastic Robotics Lab at IISc, Bangalore

### ISSUE THREAD

**Issue by aditya-shirwatkar** [curieuxjy/Awesome_Quadrupedal_Robots#2]
Hi, aweome repo!

Can you please add this lab's youtube and name in the #Labs section of the Readme. And if its not too much work then some of their papers too 😊 

- [Stochastic Robotics Lab (StochLab), IISc](https://www.stochlab.com/)
- [YouTube](https://www.youtube.com/channel/UC4SBmq_fVgzyaqHHyITkSjA)

Thanks

**Comment by curieuxjy** [comment]
Hello! Sorry for the late check.
Thank you for your suggestion!
